/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tdl.tdl.Model#getCompositeTasks <em>Composite Tasks</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.Model#getRobots <em>Robots</em>}</li>
 * </ul>
 *
 * @see org.xtext.tdl.tdl.TdlPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Composite Tasks</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tdl.tdl.CompositeTask}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Composite Tasks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Composite Tasks</em>' containment reference list.
   * @see org.xtext.tdl.tdl.TdlPackage#getModel_CompositeTasks()
   * @model containment="true"
   * @generated
   */
  EList<CompositeTask> getCompositeTasks();

  /**
   * Returns the value of the '<em><b>Robots</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tdl.tdl.Robot}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Robots</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots</em>' containment reference list.
   * @see org.xtext.tdl.tdl.TdlPackage#getModel_Robots()
   * @model containment="true"
   * @generated
   */
  EList<Robot> getRobots();

} // Model
