/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tdl.tdl.ParameterList#getCodeBlock <em>Code Block</em>}</li>
 * </ul>
 *
 * @see org.xtext.tdl.tdl.TdlPackage#getParameterList()
 * @model
 * @generated
 */
public interface ParameterList extends EObject
{
  /**
   * Returns the value of the '<em><b>Code Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Code Block</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Block</em>' attribute.
   * @see #setCodeBlock(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getParameterList_CodeBlock()
   * @model
   * @generated
   */
  String getCodeBlock();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.ParameterList#getCodeBlock <em>Code Block</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Block</em>' attribute.
   * @see #getCodeBlock()
   * @generated
   */
  void setCodeBlock(String value);

} // ParameterList
