/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Action Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tdl.tdl.SimpleActionReference#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleActionReference#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleActionReference#getSync <em>Sync</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleActionReference#getAfter <em>After</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleActionReference#getArguments <em>Arguments</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleActionReference#getPositional <em>Positional</em>}</li>
 * </ul>
 *
 * @see org.xtext.tdl.tdl.TdlPackage#getSimpleActionReference()
 * @model
 * @generated
 */
public interface SimpleActionReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleActionReference_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleActionReference#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleActionReference_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleActionReference#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Sync</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sync</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sync</em>' attribute.
   * @see #setSync(int)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleActionReference_Sync()
   * @model
   * @generated
   */
  int getSync();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleActionReference#getSync <em>Sync</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sync</em>' attribute.
   * @see #getSync()
   * @generated
   */
  void setSync(int value);

  /**
   * Returns the value of the '<em><b>After</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>After</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>After</em>' attribute.
   * @see #setAfter(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleActionReference_After()
   * @model
   * @generated
   */
  String getAfter();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleActionReference#getAfter <em>After</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>After</em>' attribute.
   * @see #getAfter()
   * @generated
   */
  void setAfter(String value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tdl.tdl.Argument}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arguments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference list.
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleActionReference_Arguments()
   * @model containment="true"
   * @generated
   */
  EList<Argument> getArguments();

  /**
   * Returns the value of the '<em><b>Positional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Positional</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Positional</em>' attribute.
   * @see #setPositional(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleActionReference_Positional()
   * @model
   * @generated
   */
  String getPositional();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleActionReference#getPositional <em>Positional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Positional</em>' attribute.
   * @see #getPositional()
   * @generated
   */
  void setPositional(String value);

} // SimpleActionReference
