/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.tdl.tdl.TdlFactory
 * @model kind="package"
 * @generated
 */
public interface TdlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tdl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/tdl/Tdl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tdl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TdlPackage eINSTANCE = org.xtext.tdl.tdl.impl.TdlPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.ModelImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Composite Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMPOSITE_TASKS = 0;

  /**
   * The feature id for the '<em><b>Robots</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ROBOTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.CompositeTaskImpl <em>Composite Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.CompositeTaskImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getCompositeTask()
   * @generated
   */
  int COMPOSITE_TASK = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITE_TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITE_TASK__TASKS = 1;

  /**
   * The number of structural features of the '<em>Composite Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOSITE_TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.TaskImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getTask()
   * @generated
   */
  int TASK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Simple Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__SIMPLE_ACTIONS = 1;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl <em>Simple Action Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getSimpleActionReference()
   * @generated
   */
  int SIMPLE_ACTION_REFERENCE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_REFERENCE__NAME = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_REFERENCE__ID = 1;

  /**
   * The feature id for the '<em><b>Sync</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_REFERENCE__SYNC = 2;

  /**
   * The feature id for the '<em><b>After</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_REFERENCE__AFTER = 3;

  /**
   * The feature id for the '<em><b>Arguments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_REFERENCE__ARGUMENTS = 4;

  /**
   * The feature id for the '<em><b>Positional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_REFERENCE__POSITIONAL = 5;

  /**
   * The number of structural features of the '<em>Simple Action Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_REFERENCE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.ArgumentImpl <em>Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.ArgumentImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getArgument()
   * @generated
   */
  int ARGUMENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.RobotImpl <em>Robot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.RobotImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getRobot()
   * @generated
   */
  int ROBOT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__NAME = 0;

  /**
   * The feature id for the '<em><b>Published Data</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__PUBLISHED_DATA = 1;

  /**
   * The feature id for the '<em><b>Initialization Module</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__INITIALIZATION_MODULE = 2;

  /**
   * The feature id for the '<em><b>Simple Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__SIMPLE_ACTIONS = 3;

  /**
   * The feature id for the '<em><b>Ros Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__ROS_NODES = 4;

  /**
   * The number of structural features of the '<em>Robot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.InitializationModuleImpl <em>Initialization Module</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.InitializationModuleImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getInitializationModule()
   * @generated
   */
  int INITIALIZATION_MODULE = 6;

  /**
   * The feature id for the '<em><b>Code Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZATION_MODULE__CODE_BLOCK = 0;

  /**
   * The number of structural features of the '<em>Initialization Module</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZATION_MODULE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.SimpleActionImpl <em>Simple Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.SimpleActionImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getSimpleAction()
   * @generated
   */
  int SIMPLE_ACTION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Positional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION__POSITIONAL = 2;

  /**
   * The feature id for the '<em><b>Code Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION__CODE_BLOCK = 3;

  /**
   * The number of structural features of the '<em>Simple Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_ACTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.ParameterImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.RosNodeImpl <em>Ros Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.RosNodeImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getRosNode()
   * @generated
   */
  int ROS_NODE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROS_NODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Code Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROS_NODE__CODE_BLOCK = 1;

  /**
   * The feature id for the '<em><b>Node Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROS_NODE__NODE_TYPE = 2;

  /**
   * The feature id for the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROS_NODE__NODE_NAME = 3;

  /**
   * The feature id for the '<em><b>Node Args</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROS_NODE__NODE_ARGS = 4;

  /**
   * The feature id for the '<em><b>Parameter List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROS_NODE__PARAMETER_LIST = 5;

  /**
   * The number of structural features of the '<em>Ros Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROS_NODE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.ParameterListImpl <em>Parameter List</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.ParameterListImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getParameterList()
   * @generated
   */
  int PARAMETER_LIST = 10;

  /**
   * The feature id for the '<em><b>Code Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_LIST__CODE_BLOCK = 0;

  /**
   * The number of structural features of the '<em>Parameter List</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_LIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.PublishedDataImpl <em>Published Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.PublishedDataImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getPublishedData()
   * @generated
   */
  int PUBLISHED_DATA = 11;

  /**
   * The feature id for the '<em><b>Topics</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUBLISHED_DATA__TOPICS = 0;

  /**
   * The number of structural features of the '<em>Published Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUBLISHED_DATA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.tdl.tdl.impl.TopicImpl <em>Topic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.tdl.tdl.impl.TopicImpl
   * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getTopic()
   * @generated
   */
  int TOPIC = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__NAME = 0;

  /**
   * The feature id for the '<em><b>Topic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__TOPIC = 1;

  /**
   * The number of structural features of the '<em>Topic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.tdl.tdl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.Model#getCompositeTasks <em>Composite Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Composite Tasks</em>'.
   * @see org.xtext.tdl.tdl.Model#getCompositeTasks()
   * @see #getModel()
   * @generated
   */
  EReference getModel_CompositeTasks();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.Model#getRobots <em>Robots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Robots</em>'.
   * @see org.xtext.tdl.tdl.Model#getRobots()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Robots();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.CompositeTask <em>Composite Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Composite Task</em>'.
   * @see org.xtext.tdl.tdl.CompositeTask
   * @generated
   */
  EClass getCompositeTask();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.CompositeTask#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.CompositeTask#getName()
   * @see #getCompositeTask()
   * @generated
   */
  EAttribute getCompositeTask_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.CompositeTask#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see org.xtext.tdl.tdl.CompositeTask#getTasks()
   * @see #getCompositeTask()
   * @generated
   */
  EReference getCompositeTask_Tasks();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see org.xtext.tdl.tdl.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.Task#getSimpleActions <em>Simple Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Simple Actions</em>'.
   * @see org.xtext.tdl.tdl.Task#getSimpleActions()
   * @see #getTask()
   * @generated
   */
  EReference getTask_SimpleActions();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.SimpleActionReference <em>Simple Action Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Action Reference</em>'.
   * @see org.xtext.tdl.tdl.SimpleActionReference
   * @generated
   */
  EClass getSimpleActionReference();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleActionReference#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.SimpleActionReference#getName()
   * @see #getSimpleActionReference()
   * @generated
   */
  EAttribute getSimpleActionReference_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleActionReference#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.tdl.tdl.SimpleActionReference#getId()
   * @see #getSimpleActionReference()
   * @generated
   */
  EAttribute getSimpleActionReference_Id();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleActionReference#getSync <em>Sync</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sync</em>'.
   * @see org.xtext.tdl.tdl.SimpleActionReference#getSync()
   * @see #getSimpleActionReference()
   * @generated
   */
  EAttribute getSimpleActionReference_Sync();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleActionReference#getAfter <em>After</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>After</em>'.
   * @see org.xtext.tdl.tdl.SimpleActionReference#getAfter()
   * @see #getSimpleActionReference()
   * @generated
   */
  EAttribute getSimpleActionReference_After();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.SimpleActionReference#getArguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Arguments</em>'.
   * @see org.xtext.tdl.tdl.SimpleActionReference#getArguments()
   * @see #getSimpleActionReference()
   * @generated
   */
  EReference getSimpleActionReference_Arguments();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleActionReference#getPositional <em>Positional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Positional</em>'.
   * @see org.xtext.tdl.tdl.SimpleActionReference#getPositional()
   * @see #getSimpleActionReference()
   * @generated
   */
  EAttribute getSimpleActionReference_Positional();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.Argument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Argument</em>'.
   * @see org.xtext.tdl.tdl.Argument
   * @generated
   */
  EClass getArgument();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.Argument#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.Argument#getName()
   * @see #getArgument()
   * @generated
   */
  EAttribute getArgument_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.Robot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Robot</em>'.
   * @see org.xtext.tdl.tdl.Robot
   * @generated
   */
  EClass getRobot();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.Robot#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.Robot#getName()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tdl.tdl.Robot#getPublishedData <em>Published Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Published Data</em>'.
   * @see org.xtext.tdl.tdl.Robot#getPublishedData()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_PublishedData();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tdl.tdl.Robot#getInitializationModule <em>Initialization Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initialization Module</em>'.
   * @see org.xtext.tdl.tdl.Robot#getInitializationModule()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_InitializationModule();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.Robot#getSimpleActions <em>Simple Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Simple Actions</em>'.
   * @see org.xtext.tdl.tdl.Robot#getSimpleActions()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_SimpleActions();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.Robot#getRosNodes <em>Ros Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ros Nodes</em>'.
   * @see org.xtext.tdl.tdl.Robot#getRosNodes()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_RosNodes();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.InitializationModule <em>Initialization Module</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initialization Module</em>'.
   * @see org.xtext.tdl.tdl.InitializationModule
   * @generated
   */
  EClass getInitializationModule();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.InitializationModule#getCodeBlock <em>Code Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code Block</em>'.
   * @see org.xtext.tdl.tdl.InitializationModule#getCodeBlock()
   * @see #getInitializationModule()
   * @generated
   */
  EAttribute getInitializationModule_CodeBlock();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.SimpleAction <em>Simple Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Action</em>'.
   * @see org.xtext.tdl.tdl.SimpleAction
   * @generated
   */
  EClass getSimpleAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.SimpleAction#getName()
   * @see #getSimpleAction()
   * @generated
   */
  EAttribute getSimpleAction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.SimpleAction#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see org.xtext.tdl.tdl.SimpleAction#getParameters()
   * @see #getSimpleAction()
   * @generated
   */
  EReference getSimpleAction_Parameters();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleAction#getPositional <em>Positional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Positional</em>'.
   * @see org.xtext.tdl.tdl.SimpleAction#getPositional()
   * @see #getSimpleAction()
   * @generated
   */
  EAttribute getSimpleAction_Positional();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.SimpleAction#getCodeBlock <em>Code Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code Block</em>'.
   * @see org.xtext.tdl.tdl.SimpleAction#getCodeBlock()
   * @see #getSimpleAction()
   * @generated
   */
  EAttribute getSimpleAction_CodeBlock();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see org.xtext.tdl.tdl.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.RosNode <em>Ros Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ros Node</em>'.
   * @see org.xtext.tdl.tdl.RosNode
   * @generated
   */
  EClass getRosNode();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.RosNode#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.RosNode#getName()
   * @see #getRosNode()
   * @generated
   */
  EAttribute getRosNode_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.RosNode#getCodeBlock <em>Code Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code Block</em>'.
   * @see org.xtext.tdl.tdl.RosNode#getCodeBlock()
   * @see #getRosNode()
   * @generated
   */
  EAttribute getRosNode_CodeBlock();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.RosNode#getNodeType <em>Node Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node Type</em>'.
   * @see org.xtext.tdl.tdl.RosNode#getNodeType()
   * @see #getRosNode()
   * @generated
   */
  EAttribute getRosNode_NodeType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.RosNode#getNodeName <em>Node Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node Name</em>'.
   * @see org.xtext.tdl.tdl.RosNode#getNodeName()
   * @see #getRosNode()
   * @generated
   */
  EAttribute getRosNode_NodeName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.RosNode#getNodeArgs <em>Node Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node Args</em>'.
   * @see org.xtext.tdl.tdl.RosNode#getNodeArgs()
   * @see #getRosNode()
   * @generated
   */
  EAttribute getRosNode_NodeArgs();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.tdl.tdl.RosNode#getParameterList <em>Parameter List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter List</em>'.
   * @see org.xtext.tdl.tdl.RosNode#getParameterList()
   * @see #getRosNode()
   * @generated
   */
  EReference getRosNode_ParameterList();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.ParameterList <em>Parameter List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter List</em>'.
   * @see org.xtext.tdl.tdl.ParameterList
   * @generated
   */
  EClass getParameterList();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.ParameterList#getCodeBlock <em>Code Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code Block</em>'.
   * @see org.xtext.tdl.tdl.ParameterList#getCodeBlock()
   * @see #getParameterList()
   * @generated
   */
  EAttribute getParameterList_CodeBlock();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.PublishedData <em>Published Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Published Data</em>'.
   * @see org.xtext.tdl.tdl.PublishedData
   * @generated
   */
  EClass getPublishedData();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.tdl.tdl.PublishedData#getTopics <em>Topics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Topics</em>'.
   * @see org.xtext.tdl.tdl.PublishedData#getTopics()
   * @see #getPublishedData()
   * @generated
   */
  EReference getPublishedData_Topics();

  /**
   * Returns the meta object for class '{@link org.xtext.tdl.tdl.Topic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Topic</em>'.
   * @see org.xtext.tdl.tdl.Topic
   * @generated
   */
  EClass getTopic();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.Topic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.tdl.tdl.Topic#getName()
   * @see #getTopic()
   * @generated
   */
  EAttribute getTopic_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.tdl.tdl.Topic#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Topic</em>'.
   * @see org.xtext.tdl.tdl.Topic#getTopic()
   * @see #getTopic()
   * @generated
   */
  EAttribute getTopic_Topic();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TdlFactory getTdlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.ModelImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Composite Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMPOSITE_TASKS = eINSTANCE.getModel_CompositeTasks();

    /**
     * The meta object literal for the '<em><b>Robots</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ROBOTS = eINSTANCE.getModel_Robots();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.CompositeTaskImpl <em>Composite Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.CompositeTaskImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getCompositeTask()
     * @generated
     */
    EClass COMPOSITE_TASK = eINSTANCE.getCompositeTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPOSITE_TASK__NAME = eINSTANCE.getCompositeTask_Name();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOSITE_TASK__TASKS = eINSTANCE.getCompositeTask_Tasks();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.TaskImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Simple Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__SIMPLE_ACTIONS = eINSTANCE.getTask_SimpleActions();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl <em>Simple Action Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getSimpleActionReference()
     * @generated
     */
    EClass SIMPLE_ACTION_REFERENCE = eINSTANCE.getSimpleActionReference();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION_REFERENCE__NAME = eINSTANCE.getSimpleActionReference_Name();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION_REFERENCE__ID = eINSTANCE.getSimpleActionReference_Id();

    /**
     * The meta object literal for the '<em><b>Sync</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION_REFERENCE__SYNC = eINSTANCE.getSimpleActionReference_Sync();

    /**
     * The meta object literal for the '<em><b>After</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION_REFERENCE__AFTER = eINSTANCE.getSimpleActionReference_After();

    /**
     * The meta object literal for the '<em><b>Arguments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_ACTION_REFERENCE__ARGUMENTS = eINSTANCE.getSimpleActionReference_Arguments();

    /**
     * The meta object literal for the '<em><b>Positional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION_REFERENCE__POSITIONAL = eINSTANCE.getSimpleActionReference_Positional();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.ArgumentImpl <em>Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.ArgumentImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getArgument()
     * @generated
     */
    EClass ARGUMENT = eINSTANCE.getArgument();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARGUMENT__NAME = eINSTANCE.getArgument_Name();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.RobotImpl <em>Robot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.RobotImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getRobot()
     * @generated
     */
    EClass ROBOT = eINSTANCE.getRobot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__NAME = eINSTANCE.getRobot_Name();

    /**
     * The meta object literal for the '<em><b>Published Data</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__PUBLISHED_DATA = eINSTANCE.getRobot_PublishedData();

    /**
     * The meta object literal for the '<em><b>Initialization Module</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__INITIALIZATION_MODULE = eINSTANCE.getRobot_InitializationModule();

    /**
     * The meta object literal for the '<em><b>Simple Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__SIMPLE_ACTIONS = eINSTANCE.getRobot_SimpleActions();

    /**
     * The meta object literal for the '<em><b>Ros Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__ROS_NODES = eINSTANCE.getRobot_RosNodes();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.InitializationModuleImpl <em>Initialization Module</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.InitializationModuleImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getInitializationModule()
     * @generated
     */
    EClass INITIALIZATION_MODULE = eINSTANCE.getInitializationModule();

    /**
     * The meta object literal for the '<em><b>Code Block</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIALIZATION_MODULE__CODE_BLOCK = eINSTANCE.getInitializationModule_CodeBlock();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.SimpleActionImpl <em>Simple Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.SimpleActionImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getSimpleAction()
     * @generated
     */
    EClass SIMPLE_ACTION = eINSTANCE.getSimpleAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION__NAME = eINSTANCE.getSimpleAction_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_ACTION__PARAMETERS = eINSTANCE.getSimpleAction_Parameters();

    /**
     * The meta object literal for the '<em><b>Positional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION__POSITIONAL = eINSTANCE.getSimpleAction_Positional();

    /**
     * The meta object literal for the '<em><b>Code Block</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_ACTION__CODE_BLOCK = eINSTANCE.getSimpleAction_CodeBlock();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.ParameterImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.RosNodeImpl <em>Ros Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.RosNodeImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getRosNode()
     * @generated
     */
    EClass ROS_NODE = eINSTANCE.getRosNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROS_NODE__NAME = eINSTANCE.getRosNode_Name();

    /**
     * The meta object literal for the '<em><b>Code Block</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROS_NODE__CODE_BLOCK = eINSTANCE.getRosNode_CodeBlock();

    /**
     * The meta object literal for the '<em><b>Node Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROS_NODE__NODE_TYPE = eINSTANCE.getRosNode_NodeType();

    /**
     * The meta object literal for the '<em><b>Node Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROS_NODE__NODE_NAME = eINSTANCE.getRosNode_NodeName();

    /**
     * The meta object literal for the '<em><b>Node Args</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROS_NODE__NODE_ARGS = eINSTANCE.getRosNode_NodeArgs();

    /**
     * The meta object literal for the '<em><b>Parameter List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROS_NODE__PARAMETER_LIST = eINSTANCE.getRosNode_ParameterList();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.ParameterListImpl <em>Parameter List</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.ParameterListImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getParameterList()
     * @generated
     */
    EClass PARAMETER_LIST = eINSTANCE.getParameterList();

    /**
     * The meta object literal for the '<em><b>Code Block</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_LIST__CODE_BLOCK = eINSTANCE.getParameterList_CodeBlock();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.PublishedDataImpl <em>Published Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.PublishedDataImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getPublishedData()
     * @generated
     */
    EClass PUBLISHED_DATA = eINSTANCE.getPublishedData();

    /**
     * The meta object literal for the '<em><b>Topics</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUBLISHED_DATA__TOPICS = eINSTANCE.getPublishedData_Topics();

    /**
     * The meta object literal for the '{@link org.xtext.tdl.tdl.impl.TopicImpl <em>Topic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.tdl.tdl.impl.TopicImpl
     * @see org.xtext.tdl.tdl.impl.TdlPackageImpl#getTopic()
     * @generated
     */
    EClass TOPIC = eINSTANCE.getTopic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOPIC__NAME = eINSTANCE.getTopic_Name();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOPIC__TOPIC = eINSTANCE.getTopic_Topic();

  }

} //TdlPackage
