/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.validation;

import org.xtext.tdl.validation.AbstractTdlValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TdlValidator extends AbstractTdlValidator {
}
