/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.tdl.tdl.InitializationModule;
import org.xtext.tdl.tdl.PublishedData;
import org.xtext.tdl.tdl.Robot;
import org.xtext.tdl.tdl.RosNode;
import org.xtext.tdl.tdl.SimpleAction;
import org.xtext.tdl.tdl.TdlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Robot</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tdl.tdl.impl.RobotImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.RobotImpl#getPublishedData <em>Published Data</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.RobotImpl#getInitializationModule <em>Initialization Module</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.RobotImpl#getSimpleActions <em>Simple Actions</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.RobotImpl#getRosNodes <em>Ros Nodes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RobotImpl extends MinimalEObjectImpl.Container implements Robot
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getPublishedData() <em>Published Data</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPublishedData()
   * @generated
   * @ordered
   */
  protected PublishedData publishedData;

  /**
   * The cached value of the '{@link #getInitializationModule() <em>Initialization Module</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitializationModule()
   * @generated
   * @ordered
   */
  protected InitializationModule initializationModule;

  /**
   * The cached value of the '{@link #getSimpleActions() <em>Simple Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSimpleActions()
   * @generated
   * @ordered
   */
  protected EList<SimpleAction> simpleActions;

  /**
   * The cached value of the '{@link #getRosNodes() <em>Ros Nodes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRosNodes()
   * @generated
   * @ordered
   */
  protected EList<RosNode> rosNodes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RobotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TdlPackage.Literals.ROBOT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.ROBOT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PublishedData getPublishedData()
  {
    return publishedData;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPublishedData(PublishedData newPublishedData, NotificationChain msgs)
  {
    PublishedData oldPublishedData = publishedData;
    publishedData = newPublishedData;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TdlPackage.ROBOT__PUBLISHED_DATA, oldPublishedData, newPublishedData);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPublishedData(PublishedData newPublishedData)
  {
    if (newPublishedData != publishedData)
    {
      NotificationChain msgs = null;
      if (publishedData != null)
        msgs = ((InternalEObject)publishedData).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TdlPackage.ROBOT__PUBLISHED_DATA, null, msgs);
      if (newPublishedData != null)
        msgs = ((InternalEObject)newPublishedData).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TdlPackage.ROBOT__PUBLISHED_DATA, null, msgs);
      msgs = basicSetPublishedData(newPublishedData, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.ROBOT__PUBLISHED_DATA, newPublishedData, newPublishedData));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InitializationModule getInitializationModule()
  {
    return initializationModule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitializationModule(InitializationModule newInitializationModule, NotificationChain msgs)
  {
    InitializationModule oldInitializationModule = initializationModule;
    initializationModule = newInitializationModule;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TdlPackage.ROBOT__INITIALIZATION_MODULE, oldInitializationModule, newInitializationModule);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInitializationModule(InitializationModule newInitializationModule)
  {
    if (newInitializationModule != initializationModule)
    {
      NotificationChain msgs = null;
      if (initializationModule != null)
        msgs = ((InternalEObject)initializationModule).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TdlPackage.ROBOT__INITIALIZATION_MODULE, null, msgs);
      if (newInitializationModule != null)
        msgs = ((InternalEObject)newInitializationModule).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TdlPackage.ROBOT__INITIALIZATION_MODULE, null, msgs);
      msgs = basicSetInitializationModule(newInitializationModule, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.ROBOT__INITIALIZATION_MODULE, newInitializationModule, newInitializationModule));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<SimpleAction> getSimpleActions()
  {
    if (simpleActions == null)
    {
      simpleActions = new EObjectContainmentEList<SimpleAction>(SimpleAction.class, this, TdlPackage.ROBOT__SIMPLE_ACTIONS);
    }
    return simpleActions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<RosNode> getRosNodes()
  {
    if (rosNodes == null)
    {
      rosNodes = new EObjectContainmentEList<RosNode>(RosNode.class, this, TdlPackage.ROBOT__ROS_NODES);
    }
    return rosNodes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TdlPackage.ROBOT__PUBLISHED_DATA:
        return basicSetPublishedData(null, msgs);
      case TdlPackage.ROBOT__INITIALIZATION_MODULE:
        return basicSetInitializationModule(null, msgs);
      case TdlPackage.ROBOT__SIMPLE_ACTIONS:
        return ((InternalEList<?>)getSimpleActions()).basicRemove(otherEnd, msgs);
      case TdlPackage.ROBOT__ROS_NODES:
        return ((InternalEList<?>)getRosNodes()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TdlPackage.ROBOT__NAME:
        return getName();
      case TdlPackage.ROBOT__PUBLISHED_DATA:
        return getPublishedData();
      case TdlPackage.ROBOT__INITIALIZATION_MODULE:
        return getInitializationModule();
      case TdlPackage.ROBOT__SIMPLE_ACTIONS:
        return getSimpleActions();
      case TdlPackage.ROBOT__ROS_NODES:
        return getRosNodes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TdlPackage.ROBOT__NAME:
        setName((String)newValue);
        return;
      case TdlPackage.ROBOT__PUBLISHED_DATA:
        setPublishedData((PublishedData)newValue);
        return;
      case TdlPackage.ROBOT__INITIALIZATION_MODULE:
        setInitializationModule((InitializationModule)newValue);
        return;
      case TdlPackage.ROBOT__SIMPLE_ACTIONS:
        getSimpleActions().clear();
        getSimpleActions().addAll((Collection<? extends SimpleAction>)newValue);
        return;
      case TdlPackage.ROBOT__ROS_NODES:
        getRosNodes().clear();
        getRosNodes().addAll((Collection<? extends RosNode>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TdlPackage.ROBOT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TdlPackage.ROBOT__PUBLISHED_DATA:
        setPublishedData((PublishedData)null);
        return;
      case TdlPackage.ROBOT__INITIALIZATION_MODULE:
        setInitializationModule((InitializationModule)null);
        return;
      case TdlPackage.ROBOT__SIMPLE_ACTIONS:
        getSimpleActions().clear();
        return;
      case TdlPackage.ROBOT__ROS_NODES:
        getRosNodes().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TdlPackage.ROBOT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TdlPackage.ROBOT__PUBLISHED_DATA:
        return publishedData != null;
      case TdlPackage.ROBOT__INITIALIZATION_MODULE:
        return initializationModule != null;
      case TdlPackage.ROBOT__SIMPLE_ACTIONS:
        return simpleActions != null && !simpleActions.isEmpty();
      case TdlPackage.ROBOT__ROS_NODES:
        return rosNodes != null && !rosNodes.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //RobotImpl
