/*
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.tdl.ui.internal.TdlActivator;

public class TdlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TdlActivator.getInstance().getInjector("org.xtext.tdl.Tdl");
	}

}
