/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.tdl.ui.AbstractTdlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TdlUiModule extends AbstractTdlUiModule {
  public TdlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
