/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl;

import org.xtext.tdl.AbstractTdlRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TdlRuntimeModule extends AbstractTdlRuntimeModule {
}
