/*
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTdlScopeProvider extends DelegatingScopeProvider {
}
