/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.tdl.TdlRuntimeModule;
import org.xtext.tdl.TdlStandaloneSetup;
import org.xtext.tdl.ide.TdlIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class TdlIdeSetup extends TdlStandaloneSetup {
  @Override
  public Injector createInjector() {
    TdlRuntimeModule _tdlRuntimeModule = new TdlRuntimeModule();
    TdlIdeModule _tdlIdeModule = new TdlIdeModule();
    return Guice.createInjector(Modules2.mixin(_tdlRuntimeModule, _tdlIdeModule));
  }
}
