/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.ide;

import org.xtext.tdl.ide.AbstractTdlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TdlIdeModule extends AbstractTdlIdeModule {
}
