/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tdl.tdl.SimpleAction#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleAction#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleAction#getPositional <em>Positional</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.SimpleAction#getCodeBlock <em>Code Block</em>}</li>
 * </ul>
 *
 * @see org.xtext.tdl.tdl.TdlPackage#getSimpleAction()
 * @model
 * @generated
 */
public interface SimpleAction extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleAction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.tdl.tdl.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleAction_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Positional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Positional</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Positional</em>' attribute.
   * @see #setPositional(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleAction_Positional()
   * @model
   * @generated
   */
  String getPositional();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleAction#getPositional <em>Positional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Positional</em>' attribute.
   * @see #getPositional()
   * @generated
   */
  void setPositional(String value);

  /**
   * Returns the value of the '<em><b>Code Block</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Code Block</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Block</em>' attribute.
   * @see #setCodeBlock(String)
   * @see org.xtext.tdl.tdl.TdlPackage#getSimpleAction_CodeBlock()
   * @model
   * @generated
   */
  String getCodeBlock();

  /**
   * Sets the value of the '{@link org.xtext.tdl.tdl.SimpleAction#getCodeBlock <em>Code Block</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Block</em>' attribute.
   * @see #getCodeBlock()
   * @generated
   */
  void setCodeBlock(String value);

} // SimpleAction
