/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.tdl.tdl.Parameter;
import org.xtext.tdl.tdl.SimpleAction;
import org.xtext.tdl.tdl.TdlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Action</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionImpl#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionImpl#getPositional <em>Positional</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionImpl#getCodeBlock <em>Code Block</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SimpleActionImpl extends MinimalEObjectImpl.Container implements SimpleAction
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected EList<Parameter> parameters;

  /**
   * The default value of the '{@link #getPositional() <em>Positional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPositional()
   * @generated
   * @ordered
   */
  protected static final String POSITIONAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPositional() <em>Positional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPositional()
   * @generated
   * @ordered
   */
  protected String positional = POSITIONAL_EDEFAULT;

  /**
   * The default value of the '{@link #getCodeBlock() <em>Code Block</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeBlock()
   * @generated
   * @ordered
   */
  protected static final String CODE_BLOCK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCodeBlock() <em>Code Block</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCodeBlock()
   * @generated
   * @ordered
   */
  protected String codeBlock = CODE_BLOCK_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleActionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TdlPackage.Literals.SIMPLE_ACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Parameter> getParameters()
  {
    if (parameters == null)
    {
      parameters = new EObjectContainmentEList<Parameter>(Parameter.class, this, TdlPackage.SIMPLE_ACTION__PARAMETERS);
    }
    return parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPositional()
  {
    return positional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPositional(String newPositional)
  {
    String oldPositional = positional;
    positional = newPositional;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION__POSITIONAL, oldPositional, positional));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getCodeBlock()
  {
    return codeBlock;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCodeBlock(String newCodeBlock)
  {
    String oldCodeBlock = codeBlock;
    codeBlock = newCodeBlock;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION__CODE_BLOCK, oldCodeBlock, codeBlock));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION__PARAMETERS:
        return ((InternalEList<?>)getParameters()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION__NAME:
        return getName();
      case TdlPackage.SIMPLE_ACTION__PARAMETERS:
        return getParameters();
      case TdlPackage.SIMPLE_ACTION__POSITIONAL:
        return getPositional();
      case TdlPackage.SIMPLE_ACTION__CODE_BLOCK:
        return getCodeBlock();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION__NAME:
        setName((String)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION__PARAMETERS:
        getParameters().clear();
        getParameters().addAll((Collection<? extends Parameter>)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION__POSITIONAL:
        setPositional((String)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION__CODE_BLOCK:
        setCodeBlock((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TdlPackage.SIMPLE_ACTION__PARAMETERS:
        getParameters().clear();
        return;
      case TdlPackage.SIMPLE_ACTION__POSITIONAL:
        setPositional(POSITIONAL_EDEFAULT);
        return;
      case TdlPackage.SIMPLE_ACTION__CODE_BLOCK:
        setCodeBlock(CODE_BLOCK_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TdlPackage.SIMPLE_ACTION__PARAMETERS:
        return parameters != null && !parameters.isEmpty();
      case TdlPackage.SIMPLE_ACTION__POSITIONAL:
        return POSITIONAL_EDEFAULT == null ? positional != null : !POSITIONAL_EDEFAULT.equals(positional);
      case TdlPackage.SIMPLE_ACTION__CODE_BLOCK:
        return CODE_BLOCK_EDEFAULT == null ? codeBlock != null : !CODE_BLOCK_EDEFAULT.equals(codeBlock);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", positional: ");
    result.append(positional);
    result.append(", codeBlock: ");
    result.append(codeBlock);
    result.append(')');
    return result.toString();
  }

} //SimpleActionImpl
