/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl.tdl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.tdl.tdl.Argument;
import org.xtext.tdl.tdl.SimpleActionReference;
import org.xtext.tdl.tdl.TdlPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Action Reference</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl#getSync <em>Sync</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl#getAfter <em>After</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl#getArguments <em>Arguments</em>}</li>
 *   <li>{@link org.xtext.tdl.tdl.impl.SimpleActionReferenceImpl#getPositional <em>Positional</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SimpleActionReferenceImpl extends MinimalEObjectImpl.Container implements SimpleActionReference
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getSync() <em>Sync</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSync()
   * @generated
   * @ordered
   */
  protected static final int SYNC_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSync() <em>Sync</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSync()
   * @generated
   * @ordered
   */
  protected int sync = SYNC_EDEFAULT;

  /**
   * The default value of the '{@link #getAfter() <em>After</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAfter()
   * @generated
   * @ordered
   */
  protected static final String AFTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAfter() <em>After</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAfter()
   * @generated
   * @ordered
   */
  protected String after = AFTER_EDEFAULT;

  /**
   * The cached value of the '{@link #getArguments() <em>Arguments</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArguments()
   * @generated
   * @ordered
   */
  protected EList<Argument> arguments;

  /**
   * The default value of the '{@link #getPositional() <em>Positional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPositional()
   * @generated
   * @ordered
   */
  protected static final String POSITIONAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPositional() <em>Positional</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPositional()
   * @generated
   * @ordered
   */
  protected String positional = POSITIONAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleActionReferenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TdlPackage.Literals.SIMPLE_ACTION_REFERENCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION_REFERENCE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION_REFERENCE__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSync()
  {
    return sync;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSync(int newSync)
  {
    int oldSync = sync;
    sync = newSync;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION_REFERENCE__SYNC, oldSync, sync));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAfter()
  {
    return after;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAfter(String newAfter)
  {
    String oldAfter = after;
    after = newAfter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION_REFERENCE__AFTER, oldAfter, after));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Argument> getArguments()
  {
    if (arguments == null)
    {
      arguments = new EObjectContainmentEList<Argument>(Argument.class, this, TdlPackage.SIMPLE_ACTION_REFERENCE__ARGUMENTS);
    }
    return arguments;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPositional()
  {
    return positional;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPositional(String newPositional)
  {
    String oldPositional = positional;
    positional = newPositional;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TdlPackage.SIMPLE_ACTION_REFERENCE__POSITIONAL, oldPositional, positional));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ARGUMENTS:
        return ((InternalEList<?>)getArguments()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION_REFERENCE__NAME:
        return getName();
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ID:
        return getId();
      case TdlPackage.SIMPLE_ACTION_REFERENCE__SYNC:
        return getSync();
      case TdlPackage.SIMPLE_ACTION_REFERENCE__AFTER:
        return getAfter();
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ARGUMENTS:
        return getArguments();
      case TdlPackage.SIMPLE_ACTION_REFERENCE__POSITIONAL:
        return getPositional();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION_REFERENCE__NAME:
        setName((String)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ID:
        setId((String)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__SYNC:
        setSync((Integer)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__AFTER:
        setAfter((String)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ARGUMENTS:
        getArguments().clear();
        getArguments().addAll((Collection<? extends Argument>)newValue);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__POSITIONAL:
        setPositional((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION_REFERENCE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ID:
        setId(ID_EDEFAULT);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__SYNC:
        setSync(SYNC_EDEFAULT);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__AFTER:
        setAfter(AFTER_EDEFAULT);
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ARGUMENTS:
        getArguments().clear();
        return;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__POSITIONAL:
        setPositional(POSITIONAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TdlPackage.SIMPLE_ACTION_REFERENCE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case TdlPackage.SIMPLE_ACTION_REFERENCE__SYNC:
        return sync != SYNC_EDEFAULT;
      case TdlPackage.SIMPLE_ACTION_REFERENCE__AFTER:
        return AFTER_EDEFAULT == null ? after != null : !AFTER_EDEFAULT.equals(after);
      case TdlPackage.SIMPLE_ACTION_REFERENCE__ARGUMENTS:
        return arguments != null && !arguments.isEmpty();
      case TdlPackage.SIMPLE_ACTION_REFERENCE__POSITIONAL:
        return POSITIONAL_EDEFAULT == null ? positional != null : !POSITIONAL_EDEFAULT.equals(positional);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", id: ");
    result.append(id);
    result.append(", sync: ");
    result.append(sync);
    result.append(", after: ");
    result.append(after);
    result.append(", positional: ");
    result.append(positional);
    result.append(')');
    return result.toString();
  }

} //SimpleActionReferenceImpl
