/**
 * generated by Xtext 2.12.0
 */
package org.xtext.tdl;

import org.xtext.tdl.TdlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TdlStandaloneSetup extends TdlStandaloneSetupGenerated {
  public static void doSetup() {
    new TdlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
